title: Chamodi Samaraweera
logo: https://github.com/chamodis/chamodis.github.io/blob/main/pp.jpg
description: I am a Biotechnology undergraduate with a strong academic background and laboratory skills who consider myself a responsible,motivated and orderly person. I am looking forward for my first work experience as a pharmaceutical researcher to contribute drug discovery and development processes
show downloads: true
theme: jekyll-theme-hacker
