title: Chamodi Samaraweera
logo: pp.jpg
description: I am a Biotechnology undergraduate with a strong academic background and laboratory skills who consider myself a responsible,motivated and orderly person. I am looking forward for my first work experienceas as a pharmaceutical researcher to contribute drug discovery and development processes
show downloads: As1 HS23192164 R.P.C.K.SAMARAWEERA
theme: jekyll-theme-slate
